// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzgdqwTgRAeanMKfNOh2PfBvZ6W1N1hW0',
    appId: '1:49474296509:web:c0768e0bf8fbf05bfeb5d4',
    messagingSenderId: '49474296509',
    projectId: 'order-and-delivery-app-8835d',
    authDomain: 'order-and-delivery-app-8835d.firebaseapp.com',
    storageBucket: 'order-and-delivery-app-8835d.firebasestorage.app',
    measurementId: 'G-Y25347NVFD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfFk9Hq2lJgysON8kLuQV_LCdQrgQzJF8',
    appId: '1:49474296509:android:117dcd938186e1fdfeb5d4',
    messagingSenderId: '49474296509',
    projectId: 'order-and-delivery-app-8835d',
    storageBucket: 'order-and-delivery-app-8835d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAengND_-q2XtgmsqL69imAYVS9tYNWGq8',
    appId: '1:49474296509:ios:90596279d69414defeb5d4',
    messagingSenderId: '49474296509',
    projectId: 'order-and-delivery-app-8835d',
    storageBucket: 'order-and-delivery-app-8835d.firebasestorage.app',
    iosClientId: '49474296509-oi0h86a1fc85h0vk3tqnnudvgp68qe7g.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterOrderAndDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAengND_-q2XtgmsqL69imAYVS9tYNWGq8',
    appId: '1:49474296509:ios:90596279d69414defeb5d4',
    messagingSenderId: '49474296509',
    projectId: 'order-and-delivery-app-8835d',
    storageBucket: 'order-and-delivery-app-8835d.firebasestorage.app',
    iosClientId: '49474296509-oi0h86a1fc85h0vk3tqnnudvgp68qe7g.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterOrderAndDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzgdqwTgRAeanMKfNOh2PfBvZ6W1N1hW0',
    appId: '1:49474296509:web:4d8040c16cf43f5cfeb5d4',
    messagingSenderId: '49474296509',
    projectId: 'order-and-delivery-app-8835d',
    authDomain: 'order-and-delivery-app-8835d.firebaseapp.com',
    storageBucket: 'order-and-delivery-app-8835d.firebasestorage.app',
    measurementId: 'G-935SMNSDV9',
  );
}
